import PolicyLayout from '@/components/PolicyLayout';

export default function RefundPage() {
  return (
    <PolicyLayout title="Return & Refund Policy">
      <div className="prose dark:prose-invert max-w-none">
        <p className="text-lg text-gray-600 dark:text-gray-300">
          Last updated: <strong>18/02/2025</strong>
        </p>

        <p>
          Thank you for shopping at <strong>DataGrid Softwares LLP</strong>.
        </p>

        <p>
          The following terms are applicable for any products that you have
          purchased from us.
        </p>

        <h2>
          <strong>Eligibility for Refunds</strong>
        </h2>

        <p>We offer refunds under the following circumstances:</p>

        <ul>
          <li>
            If the service is not delivered as promised due to an error on our
            end.
          </li>
          <li>
            If a technical issue caused by our platform prevents you from
            accessing the features you paid for, and the issue cannot be resolved
            within a reasonable timeframe.
          </li>
          <li>
            If you cancel your subscription within the refund period outlined
            below.
          </li>
        </ul>

        <h2>
          <strong>Refund Period</strong>
        </h2>

        <p>
          Refund requests must be made within <strong>30</strong> days of the
          payment date. Requests made after this period will not be eligible for a
          refund.
        </p>

        <h2>
          <strong>Non-Refundable Cases</strong>
        </h2>

        <p>Refunds will not be granted under the following conditions:</p>

        <ul>
          <li>
            If you change your mind after purchasing a subscription or service.
          </li>
          <li>If you fail to use the service during the subscription period.</li>
          <li>
            If the issue is caused by third-party software or tools not affiliated
            with our platform.
          </li>
        </ul>

        <h2>
          <strong>Refund Process</strong>
        </h2>

        <p>To request a refund, please follow these steps:</p>

        <ol>
          <li>
            Contact our support team at{" "}
            <a href="mailto:admin@datagrids.in">admin@datagrids.in</a>.
          </li>
          <li>
            Provide your payment receipt, order ID, and a detailed explanation of
            the issue.
          </li>
          <li>
            Our team will review your request and respond within 3-5 business
            days.
          </li>
          <li>
            If your request is approved, the refund will be processed to your
            original payment method within 7-10 business days.
          </li>
          <li>
            This has been generated by{" "}
            <a href="https://dodopayments.com">dodopayments.com</a>
          </li>
        </ol>

        <h2>
          <strong>Contact Us</strong>
        </h2>

        <p>
          If you have any questions about this Refund Policy or require
          assistance, please reach out to us:
        </p>

        <p>
          Email: <a href="mailto:admin@datagrids.in">admin@datagrids.in</a>
        </p>
      </div>
    </PolicyLayout>
  );
}
