import PolicyLayout from "@/components/PolicyLayout";

export default function PrivacyPolicy() {
  return (
    <PolicyLayout title="Privacy Policy">
      <div className="prose dark:prose-invert max-w-none">
        <div>
          <p>
            Our Privacy Policy was last updated on <strong>12/08/2026</strong>.
          </p>

          <p>
            At <strong>DataGrid Softwares LLP</strong>, one of our main
            priorities is the privacy of our visitors. This Privacy Policy
            document contains types of information that is collected and
            recorded by <strong>DataGrid Softwares LLP</strong> and how we use
            it.
          </p>

          <p>
            If you have additional questions or require more information about
            our Privacy Policy, do not hesitate to contact us at{" "}
            <a href="mailto:admin@datagrids.in">admin@datagrids.in</a>.
          </p>

          <p>
            This Privacy Policy applies only to our online activities and is
            valid for visitors to our website with regards to the information
            that they shared and/or collected on{" "}
            <a href="datagrids.in" target="_blank" rel="noopener noreferrer">
              datagrids.in
            </a>
            . Except where stated otherwise, this policy is not applicable to
            any information collected offline or via channels other than this
            website. Our browser extensions are covered by the{" "}
            <a href="#browser-extensions">Browser Extensions</a> section below.
          </p>

          <h2>
            <strong>Consent</strong>
          </h2>

          <p>
            By using our website, you hereby consent to our Privacy Policy and
            agree to its terms.
          </p>

          <h2>
            <strong>Information We Collect</strong>
          </h2>

          <p>
            The personal information that you are asked to provide, and the
            reasons why you are asked to provide it, will be made clear to you
            at the point we ask you to provide your personal information. This
            policy has been generated by
            <a href="https://dodopayments.com">dodopayments.com</a>.
          </p>

          <p>
            If you contact us directly, we may receive additional information
            about you such as your name, email address, phone number, the
            contents of the message and/or attachments you may send us, and any
            other information you may choose to provide.
          </p>

          <p>
            When you register for an account, we may ask for your contact
            information, including items such as name, company name, address,
            email address, and telephone number.
          </p>

          <h2>
            <strong>How We Use Your Information</strong>
          </h2>

          <p>
            We use the information we collect in various ways, including to:
          </p>

          <ul>
            <li>Provide, operate, and maintain our website.</li>
            <li>Improve, personalize, and expand our website.</li>
            <li>Understand and analyze how you use our website.</li>
            <li>
              Develop new products, services, features, and functionality.
            </li>
            <li>
              Communicate with you, either directly or through one of our
              partners, including for customer service, to provide you with
              updates and other information relating to the website, and for
              marketing and promotional purposes.
            </li>
            <li>Send you emails.</li>
            <li>Find and prevent fraud.</li>
          </ul>

          <h2>
            <strong>Log Files</strong>
          </h2>

          <p>
            <strong>DataGrid Softwares LLP</strong> follows a standard procedure
            of using log files. These files log visitors when they visit
            websites. All hosting companies do this as part of hosting
            services&apos; analytics.
          </p>

          <p>
            The information collected by log files includes internet protocol
            (IP) addresses, browser type, Internet Service Provider (ISP), date
            and time stamp, referring/exit pages, and possibly the number of
            clicks. These are not linked to any information that is personally
            identifiable. The purpose of the information is for analyzing
            trends, administering the site, tracking users&apos; movement on the
            website, and gathering demographic information.
          </p>

          <h2>
            <strong>Cookies and Web Beacons</strong>
          </h2>

          <p>
            Like any other website, <strong>DataGrid Softwares LLP</strong> uses
            &apos;cookies&apos;. These cookies are used to store information
            including visitors&apos; preferences, and the pages on the website
            that the visitor accessed or visited.
          </p>

          <p>
            The information is used to optimize the users&apos; experience by
            customizing our web page content based on visitors&apos; browser
            type and/or other information.
          </p>

          <h2>
            <strong>Advertising Partners Privacy Policies</strong>
          </h2>

          <p>
            Third-party ad servers or ad networks use technologies like cookies,
            JavaScript, or Web Beacons that are used in their respective
            advertisements and links that appear on{" "}
            <strong>DataGrid Softwares LLP</strong>, which are sent directly to
            users&apos; browsers. They automatically receive your IP address
            when this occurs. These technologies are used to measure the
            effectiveness of their advertising campaigns and/or to personalize
            the advertising content that you see on websites that you visit.
          </p>

          <p>
            Note that <strong>DataGrid Softwares LLP</strong> has no access to
            or control over these cookies that are used by third-party
            advertisers.
          </p>

          <h2>
            <strong>Third Party Privacy Policies</strong>
          </h2>

          <p>
            <strong>DataGrid Softwares LLP</strong>&apos;s Privacy Policy does
            not apply to other advertisers or websites. Thus, we are advising
            you to consult the respective Privacy Policies of these third-party
            ad servers for more detailed information. It may include their
            practices and instructions about how to opt-out of certain options.
          </p>

          <p>
            You can choose to disable cookies through your individual browser
            options. This is recommended by dodopayments.com. To know more
            detailed information about cookie management with specific web
            browsers, it can be found at the browsers&apos; respective websites.
          </p>

          <h2>
            <strong>
              CCPA Privacy Rights (Do Not Sell My Personal Information)
            </strong>
          </h2>

          <p>
            Under the CCPA, among other rights, California consumers have the
            right to:
          </p>

          <ul>
            <li>
              Request that a business that collects a consumer&apos;s personal
              data disclose the categories and specific pieces of personal data
              that a business has collected about consumers.
            </li>
            <li>
              Request that a business delete any personal data about the
              consumer that a business has collected.
            </li>
            <li>
              Request that a business that sells a consumer&apos;s personal
              data, not sell the consumer&apos;s personal data.
            </li>
          </ul>

          <p>
            If you make a request, we have one month to respond to you. If you
            would like to exercise any of these rights, please contact us.
          </p>

          <h2>
            <strong>GDPR Data Protection Rights</strong>
          </h2>

          <p>
            We want to ensure you are fully aware of all of your data protection
            rights. Every user is entitled to the following:
          </p>

          <ul>
            <li>
              <strong>The right to access:</strong> You have the right to
              request copies of your personal data. We may charge you a small
              fee for this service.
            </li>
            <li>
              <strong>The right to rectification:</strong> You have the right to
              request that we correct any information you believe is inaccurate.
              You also have the right to request that we complete the
              information you believe is incomplete.
            </li>
            <li>
              <strong>The right to erasure:</strong> You have the right to
              request that we erase your personal data, under certain
              conditions.
            </li>
            <li>
              <strong>The right to restrict processing:</strong> You have the
              right to request that we restrict the processing of your personal
              data, under certain conditions.
            </li>
            <li>
              <strong>The right to object to processing:</strong> You have the
              right to object to our processing of your personal data, under
              certain conditions.
            </li>
            <li>
              <strong>The right to data portability:</strong> You have the right
              to request that we transfer the data that we have collected to
              another organization, or directly to you, under certain
              conditions.
            </li>
          </ul>

          <p>
            If you make a request, we have one month to respond to you. If you
            would like to exercise any of these rights, please contact us.
          </p>

          <h2 id="browser-extensions">
            <strong>Browser Extensions</strong>
          </h2>

          <p>
            This section covers browser extensions published by{" "}
            <strong>DataGrid Softwares LLP</strong>, currently{" "}
            <strong>Notes Everywhere</strong>, an extension that lets you
            highlight text on a web page and attach comment threads to it. It
            applies in addition to the rest of this policy.
          </p>

          <h3>
            <strong>We do not collect anything</strong>
          </h3>

          <p>
            Notes Everywhere has no server. Your notes, the pages you visit and
            the text you highlight are never transmitted to{" "}
            <strong>DataGrid Softwares LLP</strong> or to anyone else. Nothing
            is collected, sold, shared, or used for advertising or analytics.
          </p>

          <h3>
            <strong>What the extension stores, and where</strong>
          </h3>

          <p>
            Everything the extension saves is stored on your own computer using
            Chrome&apos;s local extension storage:
          </p>

          <ul>
            <li>
              Your notes — the quoted text, your comments, colours and
              timestamps.
            </li>
            <li>
              The address of the page a note belongs to, so the note can be
              found again.
            </li>
            <li>
              Your Google name, email address and profile picture, only if you
              choose to sign in.
            </li>
            <li>
              Your Google sign-in token, only if you choose to sign in. It is
              used solely to identify you to Google and is erased when you sign
              out.
            </li>
          </ul>

          <p>Uninstalling the extension deletes all of it.</p>

          <h3>
            <strong>Google sign-in is optional</strong>
          </h3>

          <p>
            The extension works fully without signing in; notes are then
            authored as “Local user”. If you do sign in, the extension requests
            the openid, email and profile scopes and makes a single request to
            Google&apos;s user information endpoint to read your name, email
            address and picture. That information is used for one purpose —
            putting your name on the comments you write — is stored only on your
            device, and is not transmitted anywhere else. Signing out revokes
            the token with Google and erases the stored profile.
          </p>

          <h3>
            <strong>Why the extension needs access to pages you visit</strong>
          </h3>

          <p>
            To attach a note to a phrase, the extension must read the text of
            the page you are on; to display a note, it must draw on that page.
            Page content is read inside your browser, used only to locate your
            notes, and never transmitted. The permissions it requests are
            storage (saving notes locally), identity (optional sign-in),
            activeTab and contextMenus (the “Add note” action), and access to
            the sites you choose to annotate.
          </p>

          <h3>
            <strong>Notes are embedded in the page you are viewing</strong>
          </h3>

          <p>
            By design, your notes are written into the page you are reading — as
            a structured data block, as hidden semantic HTML, and through a
            JavaScript interface — so that scripts and AI agents acting on your
            behalf can read them. This happens only inside your own browser tab
            and sends nothing to the website you are visiting. Please note that
            other extensions installed in your browser, or scripts you
            deliberately run against the page, can read this data, in the same
            way they can read anything else on the page.
          </p>

          <h3>
            <strong>Questions</strong>
          </h3>

          <p>
            For anything relating to the privacy practices of our extensions,
            contact us at{" "}
            <a href="mailto:admin@datagrids.in">admin@datagrids.in</a>.
          </p>

          <h2>
            <strong>Children&apos;s Information</strong>
          </h2>

          <p>
            Another part of our priority is adding protection for children while
            using the internet. We encourage parents and guardians to observe,
            participate in, and/or monitor and guide their online activity.
            These guidelines have been generated by dodopayments.com.
          </p>

          <p>
            <strong>DataGrid Softwares LLP</strong> does not knowingly collect
            any Personal Identifiable Information from children under the age of
            13. If you think that your child provided this kind of information
            on our website, we strongly encourage you to contact us immediately
            and we will do our best efforts to promptly remove such information
            from our records.
          </p>
        </div>
      </div>
    </PolicyLayout>
  );
}
